service: FizzBurgerChallenge

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 192
  stage: ${opt:stage, 'local'}
  region: ${opt:region, 'us-east-1'}
  endpointType: REGIONAL
  apiName: FizzBurgerChallenge API
  environment:
    NODE_ENV: ${env:NODE_ENV}
    MONGO_CONNECTION_URI: ${env:MONGO_CONNECTION_URI}
    MONGODB_NAME: ${env:MONGODB_NAME}

custom:
  serverless-offline:
    port: 4000
    printOutput: true
    cacheInvalidationRegex: 'node_modules/'

functions:
  main:
    handler: dist/lambda.handler
    events:
      - http:
          integration: lambda-proxy
          method: any
          path: /{any+}

plugins:
  - serverless-offline
  - serverless-plugin-optimize
  - serverless-dotenv-plugin

package:
  exclude:
    - .env
    - .github
    - .husky
    - .babelrc
    - .dockerignore
    - .eslintignore
    - .eslintrc.js
    - .gitignore
    - .env.example
    - .prettierrc
    - coverage/**
    - src/**
    - test/**
    - postman/**
    - docker-compose.yml
    - Dockerfile
    - commitlint.config
    - Makefile
    - CHANGELOG.md
    - README.md
