on:
  push:
    branches:
      - develop

name: deploy challenge fizz burger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create .env file
        run: |
          echo "NODE_ENV='develop'" >> .env
          echo "MONGODB_NAME=burger" >> .env
          echo "MONGO_CONNECTION_URI=${{ secrets.MONGO_CONNECTION_URI }}" >> .env

      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Deploy to AWS
        run: make deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
