on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  pull_request:
    types: [opened, synchronize, reopened]
name: Test, linting and formatting
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: install 18.7.0
        run: sudo n 18.7.0
      - name: Install dependencies
        run: npm install
      - name: Install Jest globally
        run: sudo npm install -g jest
      - name: check lint
        run: npm run lint
      - name: Create .env file
        run: |
          echo "NODE_ENV='develop'" >> .env
          echo "MONGODB_NAME=burger" >> .env
          echo "MONGO_CONNECTION_URI=${{ secrets.MONGO_CONNECTION_URI }}" >> .env
      - name: Run Tests
        run: npm run test
